platform :ios, '9.0'

inhibit_all_warnings!

target 'CSSNetworking' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   
  pod 'AFNetworking', '~> 3.1.0'
  pod 'YYModel', '~> 1.0.4'
  pod 'CSSModel', '~> 0.0.3'
  pod 'MJExtension', '~> 3.0.13'
  
  target 'CSSNetworkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end